// GET GALLERY
export const GET_SATELLITE_REQUEST = "GET_SATELLITE_REQUEST";
export const GET_SATELLITE_SUCCESS = "GET_SATELLITE_SUCCESS";
export const GET_SATELLITE_FAILURE = "GET_SATELLITE_FAILURE";
